name: "Godot Exporter"
description: "Godot Engine Automation Pipeline Android – Linux – MacOS – Windows – WebHTML5 – Itch.io."
author: Vinicius Guerrero & Andrea Miele
runs:
  using: docker
#   image: docker://viiniiguerrero/godot-exporter
  image: Dockerfile
branding:
  icon: upload
  color: white
