# docker-compose up -d

version: "3.9"
volumes:
  data:
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/game/build/android
    env:
      DEBIAN_FRONTEND: noninteractive
      GODOT_VERSION: 3.2.2
      EXPORT_NAME: game
      EXPORT_PATH: /game
      ROOT_PATH: /root
