# docker-compose up -d

version: "3.9"
volumes:
  data:
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/game/build/android
    env:
      GODOT_VERSION: 3.2.2
      GODOT_RELEASE: stable
      EXPORT_NAME: game
      ROOT_PATH: /root
