name: "Godot Exporter"
description: "Godot Engine Automation Pipeline Android – iOS – Linux – Mac OSX – Windows Desktop – HTML5 – Itch.io."
author: Vinicius Guerrero & Andrea Miele
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload
  color: white
