name: "Export Environment"
description: "Export Environment"
inputs:
  platform:
    description: "Godot Export Platform"
    required: true
    default: "Linux"
outputs:
  artifact-path:
    description: "Exported Artifact"
    value: ${{ steps.exported-artifact.outputs.artifact-path }}
  export-settings:
    description: "Exported Settings"
    value: ${{ steps.exported-settings.outputs.export-settings }}
  exported-game-version:
    description: "Exported Game Version"
    value: ${{ steps.exported-game-version.outputs.exported-game-version }}
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: |
        echo -e "\n Export Platform ${{inputs.platform}} \n" &&
        echo -e "\n android_sdk_path -> ${ANDROID_HOME} \n adb -> ${ANDROID_HOME}/platform-tools \n" &&  
        chmod +x ${{ github.action_path }}/export.sh && ${{ github.action_path }}/export.sh ${{inputs.platform}}
      shell: bash
    - id: exported-artifact
      run: echo "::set-output name=artifact-path::$(echo ${PROJECT_PATH}/build/${{inputs.platform}})"
      shell: bash
    - id: exported-settings
      run: echo "::set-output name=export-settings::$(echo ${PROJECT_PATH}/export_settings.zip)"
      shell: bash
    - id: exported-game-version
      run: |
        grep 'game/version' ${PROJECT_PATH}/project.godot > version.txt &&
        GAME_VERSION=$(eval "grep -Eo '[0-9]\.[0-9]\.[0-9]\.[0-9]+' version.txt") &&
        echo "::set-output name=exported-game-version::$(echo ${GAME_VERSION})"
      shell: bash
