name: "Export Environment"
description: "Export Environment"
inputs:
  platform:
    description: "Godot Export Platform"
    required: true
    default: "Linux"
  export_path:
    description: "Godot Game Path"
    required: true
    default: "game"
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.3.2"
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: |
        echo -e "\n Export Platform ${{inputs.platform}} \n" &&
        echo -e "\n android_sdk_path -> ${ANDROID_HOME} \n adb -> ${ANDROID_HOME}/platform-tools \n" &&        
        chmod +x actions/export_env/export.sh && bash actions/export_env/export.sh ${{inputs.platform}} ${{inputs.export_path}}
      shell: bash
