name: "Export Environment"
description: "Export Environment"
inputs:
  platform:
    description: "Godot Export Platform"
    required: true
    default: "Linux"
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: |
        echo -e "\n Export Platform ${{inputs.platform}} \n" &&
        echo -e "\n android_sdk_path -> ${ANDROID_HOME} \n adb -> ${ANDROID_HOME}/platform-tools \n" &&  
        ${{ github.action_path }}/export.sh ${{inputs.platform}}
      shell: bash
