name: Bash Export
on:
  push:
    branches: [dev]

env:
  EXPORT_NAME: game
  GODOT_VERSION: 3.3.1
  GODOT_DL_SUBDIR: 3.3.1
  GODOT_RELEASE: stable

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Dependencies
        working-directory: .
        run: |
          chmod +x ./setup.sh && sudo ./setup.sh
