name: "Mobile Project Export"
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: Godot Version
        required: true
        default: "3.3.2"
      godot_release:
        description: Godot Release (Mono Not Yet Supported)
        required: true
        default: "stable"
      export_name:
        description: Final Export Release Name
        required: true
        default: "export"
      export_path:
        description: Relative Project Path
        required: true
        default: "game"
      # retention_days:
      #   description: Artifact Retention In Days - Max 90 Days
      #   required: true
      #   default: "15"
      export_android:
        description: Export to Android
        required: true
        default: "true"
      itch_io_export:
        description: Export to Itch.io
        required: true
        default: "false"
      itch_io_game:
        description: Itch.io game
        required: false
        default: ""

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}
  GODOT_RELEASE: ${{ github.event.inputs.godot_release }}
  EXPORT_NAME: ${{ github.event.inputs.export_name }}
  EXPORT_PATH: ${{ github.event.inputs.export_path }}
  # EXPORT_RETENTION_DAYS: ${{ github.event.inputs.retention_days }}
  EXPORT_ANDROID: ${{ github.event.inputs.export_android }}
  ITCH_IO_GAME: ${{ github.event.inputs.itch_io_game }}
jobs:
  export:
    name: "Mobile Project Export"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    env:
      DEBIAN_FRONTEND: noninteractive
      ROOT_PATH: /github/home
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot Export Templates
        run: bash setup.sh
      ######################################################
      ### Export Builds
      ######################################################
      # Android Debug Build
      - name: Android Debug Build
        if: ${{ env.EXPORT_ANDROID=='true' }}
        run: |
          cd ${EXPORT_PATH}
          mkdir -v -p build/android
          godot --verbose --export-debug "Android" ./build/android/$EXPORT_NAME.debug.apk
      # Android Release Build
      - name: Android Release Build
        if: ${{ env.EXPORT_ANDROID=='true' }}
        env:
          K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
          K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER  }}
          K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD  }}
        run: |
          echo $K8S_SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
          cd ${EXPORT_PATH}
          sed 's@keystore/release[[:space:]]*=[[:space:]]*".*"@keystore/release = "/root/release.keystore"@g' -i export_presets.cfg
          sed 's@keystore/release_password[[:space:]]*=[[:space:]]*".*"@keystore/release_password="'$K8S_SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
          sed 's@keystore/release_user[[:space:]]*=[[:space:]]*".*"@keystore/release_user="'$K8S_SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
          godot --verbose --export "Android" ./build/android/$EXPORT_NAME.release.apk
      ######################################################
      ### Artifacts Upload
      ######################################################
      # Android Artifact
      - uses: actions/upload-artifact@v2
        name: Android Artifact Upload
        if: ${{ env.EXPORT_ANDROID=='true' }}
        with:
          name: Android
          path: ${{ env.EXPORT_PATH }}/build/android
          # retention-days: ${{ env.EXPORT_RETENTION_DAYS }}
      - uses: josephbmanley/butler-publish-itchio-action@master
        name: Publish Itch.io Android Build
        if:
          env.EXPORT_ANDROID=='true' ||
          github.event.inputs.itch_io_export=='true'
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: android
          ITCH_GAME: ${{ env.ITCH_IO_GAME }}
          ITCH_USER: ${{ secrets.ITCH_IO_USER }}
          PACKAGE: ${{ env.EXPORT_PATH }}/build/android
