name: Docker Export
on:
  push:
    branches: [docker]

jobs:
  export:
    runs-on: ubuntu-latest
    # Docker Hub Hosted Method
    container:
      image: viiniiguerrero/godot_ci
    env:
      EXPORT_NAME: game
      GODOT_VERSION: 3.2.2
      GODOT_DL_SUBDIR: 3.2.2
      GODOT_RELEASE: stable
      ROOT_PATH: github/home
    # Docker Hub Hosted Method
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Github Hosted Method
      # - name: Set Up Export Docker
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      # Github Hosted Method
      - name: Setup Godot Export Templates
        run: |
          bash setup.sh
      - name: Android Debug Build
        run: |
          cd game
          mkdir -v -p build/android
          godot --verbose --export-debug "Android" ./build/android/$EXPORT_NAME.debug.apk
      - name: Android Release Build
        env:
          K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
          K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER  }}
          K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD  }}
        run: |
          echo $K8S_SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
          cd game
          sed 's@keystore/release[[:space:]]*=[[:space:]]*".*"@keystore/release = "/root/release.keystore"@g' -i export_presets.cfg
          sed 's@keystore/release_password[[:space:]]*=[[:space:]]*".*"@keystore/release_password="'$K8S_SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
          sed 's@keystore/release_user[[:space:]]*=[[:space:]]*".*"@keystore/release_user="'$K8S_SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
          godot --verbose --export "Android" ./build/android/$EXPORT_NAME.release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: android
          path: game/build/android
