name: Export
on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest
    container: viiniiguerrero/godot_ci
    steps:
      - uses: actions/checkout@v2.3.2
      - run: ls & & pwd
