name: Export



on:

  push:

    branches: [ main ]

  

jobs:

  container:

    runs-on: ubuntu-latest

    container: vini-guerrero/ci_cd:main

    steps:

      - uses: actions/checkout@v2.3.2

      - run: ls
