name: Export
on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest
    container: viniguerrero/ci_cd:main
    steps:
      - uses: actions/checkout@v2.3.2
      - run: ls & & pwd
