name: Export
on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest 
    # container: viiniiguerrero/godot_ci:latest 
    steps: 
      - uses: actions/checkout@v2.3.2
      - name: Run Script
        working-directory: . 
        run : |
          chmod +x ./start.sh
          sudo ./start.sh
      - name: Android Debug Build
        run: |
          mkdir -v -p build/android
          echo ${{ env.GODOT_HEADLESS_BUILD }} 
