name: Export
on:
  push:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest
    # container: viiniiguerrero/godot_ci:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Run Setup Script
        # env:
        #   GODOT_VERSION: 3.3.1
        #   GODOT_DL_SUBDIR: 3.3.1
        #   GODOT_RELEASE: stable
        working-directory: .
        run: |
          echo "GODOT_VERSION=3.3.1" >> $GITHUB_ENV
          echo "GODOT_DL_SUBDIR=3.3.1" >> $GITHUB_ENV
          echo "GODOT_RELEASE=stable" >> $GITHUB_ENV
          chmod +x ./test.sh && sudo ./test.sh
      # - name: Android Debug Build
      #   run: |
      #     cd game
      #     mkdir -v -p build/android
      #     godot --verbose --export-debug "Android" ./build/android/$EXPORT_NAME.debug.apk
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: Android
      #     path: game/build/android
