name: Export
on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest 
    steps:
        uses: viiniiguerrero/godot_ci:latest 
        with:
          args: /bin/sh -c "cat /etc/hosts" 
      - uses: actions/checkout@v2.3.2
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.config/godot/
          cp /root/.config/godot/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
          echo 'export/android/debug_keystore = "/root/android-sdk/debug.keystore"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/android_sdk_path = "/root/android-sdk"' >> ~/.config/godot/editor_settings-3.tres
      - name: Android Debug Build
        run: |
          mkdir -v -p build/android
          echo ${{ env.GODOT_HEADLESS_BUILD }} 
