name: Export
on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest 
    # container: viiniiguerrero/godot_ci:latest 
    steps: 
      - uses: actions/checkout@v2.3.2
      - name: Run Setup Script
        working-directory: . 
        run : |
          chmod +x ./setup.sh && sudo ./setup.sh
      - name: Validate Environment
        run : |
          printenv
      - name: Run Export Script
        working-directory: . 
        run : |
          chmod +x ./export.sh && sudo ./export.sh
      - name: Android Debug Build
        run: |
          mkdir -v -p build/android
          echo ${{ env.GODOT_HEADLESS_BUILD }} 
