name: Export



on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  container:

    runs-on: ubuntu-latest

    container: vini-guerrero/ci_cd

    steps:

      - uses: actions/checkout@v2.3.2

      - run: ls
