name: "Push Export"
on:
  push:
    branches:
      - main
      - master
      - dev

env:
  GODOT_VERSION: 3.3.2
  GODOT_RELEASE: stable
  EXPORT_NAME: export
  EXPORT_PATH: game
  # EXPORT_RETENTION_DAYS: ${{ github.event.inputs.retention_days }}
  EXPORT_ANDROID: true
  GODOT_EXPORT_PLATFORMS: Android|Linux|MacOS|Windows
  EXPORT_PLATFORM: Android
  ANDROID_RELEASE: false
  ITCH_IO_GAME: false
  ROOT_PATH: /github/home
  K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
  K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER }}
  K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD }}

jobs:
  export:
    name: "Test Export"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export
        uses: ./
     # # Android Artifact
     # - name: Android Artifact Upload
     #   uses: actions/upload-artifact@v2
     #   with:
     #     name: Android
     #     path: ${{ github.workspace }}/artifact.zip
     #     # retention-days: ${{ env.EXPORT_RETENTION_DAYS }}
