name: "iOS Build"
on:
  workflow_dispatch:
    inputs:
      icon_path:
        description: "Icon Path"
        required: true
        default: ""

env:
  ICON_PATH: ${{ github.event.inputs.icon_path }}

jobs:
  export:
    name: "iOS Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Icon Generation Script
        run: |
          bash ls && pwd
